language: go
go:
  - 1.2
  - 1.3
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
install: make get-deps
env:
  - HADOOP_DISTRO=cdh
  - HADOOP_DISTRO=hdp
before_script:
  - export NN_PORT=9000
  - export HADOOP_NAMENODE="localhost:$NN_PORT"
  - export HADOOP_HOME="hadoop-$HADOOP_DISTRO"
  - ./setup_test_env.sh
script:
  - make test
  - cat minicluster.log
sudo: false
cache:
  - hadoop-$HADOOP_DISTRO
